/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.StudentRole;

import Education.Education;
import Education.Student.Student;
import Utiltities.GraduationStatus;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chinmaygulhane
 */
public class GraduationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Education education;
    private Student student;
    
    /**
     * Creates new form GraduationJPanel
     */
    GraduationJPanel(JPanel userProcessContainer, Education education, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.education = education; 
        this.student = student;
        setGraduationStatus();
        renderPageAccordingToGraduationStatus();
    }
    
    private void setGraduationStatus(){
        String notApplied = "";
        String graduated = "Congratulations you have Graduated";
        String rejected = "We regret to inform you that your graduation request has been declined. Please apply again.";
        String applied = "Your graduation request is being reviewed by the Authorities";
        
        if(student.getGraduationStatus() == GraduationStatus.NOTAPPLIED){
            txtGraduationStatus.setText("Not Applied");
            btnApplyGraduation.setVisible(true);
        } else if(student.getGraduationStatus() == GraduationStatus.APPLIED){
            txtGraduationStatus.setText("Applied");
            lblGraduationMessage.setText(applied);
            btnApplyGraduation.setVisible(false);
        } else if(student.getGraduationStatus() == GraduationStatus.ACCEPTED){
            txtGraduationStatus.setText("Graduated"); 
            lblGraduationMessage.setText(graduated);
            btnApplyGraduation.setVisible(false);
        } else if(student.getGraduationStatus() == GraduationStatus.REJECTED){
            txtGraduationStatus.setText("Rejected");
            lblGraduationMessage.setText(rejected);
            btnApplyGraduation.setVisible(true);
        }
    }
    
    private void renderPageAccordingToGraduationStatus(){
        String notApplied = "";
        String graduated = "Congratulations you have Graduated";
        String rejected = "We regret to inform you that your graduation request has been declined. Please apply again.";
        String inProgress = "Your graduation request is being reviewed by the Authorities";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnApplyGraduation = new javax.swing.JButton();
        txtGraduationStatus = new javax.swing.JTextField();
        lblGraduationMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Graduation Section");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Graduation Status:");

        btnApplyGraduation.setBackground(new java.awt.Color(0, 0, 0));
        btnApplyGraduation.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnApplyGraduation.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyGraduation.setText("Apply For Graduation");
        btnApplyGraduation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyGraduationActionPerformed(evt);
            }
        });

        txtGraduationStatus.setEditable(false);

        lblGraduationMessage.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGraduationMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApplyGraduation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtGraduationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGraduationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyGraduation)
                    .addComponent(btnBack))
                .addGap(43, 43, 43)
                .addComponent(lblGraduationMessage)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if(component instanceof StudentJPanel studentJPanel) {
            studentJPanel.setupStudentDashboard();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApplyGraduationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyGraduationActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to apply for graduation ?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            student.setGraduationStatus(GraduationStatus.APPLIED);
            setGraduationStatus();
        }
    }//GEN-LAST:event_btnApplyGraduationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyGraduation;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGraduationMessage;
    private javax.swing.JTextField txtGraduationStatus;
    // End of variables declaration//GEN-END:variables
}
