/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.StudentRole;

import Education.Courses.Course;
import Education.Courses.CourseSchedule;
import Education.Education;
import Education.Professor.Professor;
import Education.Student.Student;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samik
 */
public class AddCoursesJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Education education;
    private Student student;
    private String selectedTerm;

    /**
     * Creates new form AddCoursesJPanel
     */
    AddCoursesJPanel(JPanel userProcessContainer, Education education, Student student, String selectedTerm) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.education = education;
        this.student = student;
        this.selectedTerm = selectedTerm;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblViewCourse.getModel();
        dtm.setRowCount(0);
        for (CourseSchedule cs : education.getCourseScheduleDirectory().getCourseScheduleList()) {
            if ((cs.getTerm() + " " + cs.getYear()).equals(selectedTerm)) {
                for (Course c : education.getCourseDirectory().getCourseList()) {
                    for (Professor p : education.getProfessorsDirectory().getProfessorList()) {
                        if (p.getProfessorId().equals(cs.getTeachingProfessorId())) {
                            if (cs.getCourseId().equals(c.getCourseId())) {
                                Object[] row = new Object[6];
                                row[0] = c.getCourseId();
                                row[1] = c.getTopic();
                                row[2] = c.getName();
                                row[3] = p.getName();
                                row[4] = cs.getStartDate();
                                row[5] = cs.getTeachingProfessorRating();
                                dtm.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCourse = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        tblViewCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Topic", "Course Name", "Professor Name", "Schedule", "Professor Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCourse);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Search");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Find Course");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        populateSearch(txtSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnResetActionPerformed
    
    private void populateSearch(String search) {
        DefaultTableModel dtm = (DefaultTableModel) tblViewCourse.getModel();
        dtm.setRowCount(0);
        for (CourseSchedule cs : education.getCourseScheduleDirectory().getCourseScheduleList()) {
            if ((cs.getCourseId().equals(search) && (cs.getTerm() + " " + cs.getYear()).equals(selectedTerm))) {
                for (Course c : education.getCourseDirectory().getCourseList()) {
                    for (Professor p : education.getProfessorsDirectory().getProfessorList()) {
                        if (p.getProfessorId().equals(cs.getTeachingProfessorId())) {
                            if (cs.getCourseId().equals(c.getCourseId())) {
                                Object[] row = new Object[6];
                                row[0] = c.getCourseId();
                                row[1] = c.getTopic();
                                row[2] = c.getName();
                                row[3] = p.getName();
                                row[4] = cs.getStartDate();
                                row[5] = cs.getTeachingProfessorRating();
                                dtm.addRow(row);
                            }
                        }
                    }
                }
            } 
//            else {
//                for (CourseSchedule csh : education.getCourseScheduleDirectory().getCourseScheduleList()) {
//                    if ((csh.getTerm() + " " + csh.getYear()).equals(selectedTerm)) {
//                        for (Course c : education.getCourseDirectory().getCourseList()) {
//                            if (c.getTopic().equals(search)&& csh.getCourseId().equals(c.getCourseId())) {
//                                for (Professor p : education.getProfessorsDirectory().getProfessorList()) {
//                                    if (p.getProfessorId().equals(csh.getTeachingProfessorId())) {
//                                            Object[] row = new Object[6];
//                                            row[0] = c.getCourseId();
//                                            row[1] = c.getTopic();
//                                            row[2] = c.getName();
//                                            row[3] = p.getName();
//                                            row[4] = csh.getStartDate();
//                                            row[5] = csh.getTeachingProfessorRating();
//                                            dtm.addRow(row);
//                                        
//                                    }
//                                }
//                            }
//                        }
//                    }
//                }
//            }
        }
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewCourse;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
