/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.ProfessorRole;

import Education.Courses.Course;
import Education.Courses.CourseSchedule;
import Education.Education;
import Education.Professor.Professor;
import Education.Student.Student;
import java.awt.CardLayout;
import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StudentRankingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentRankingJPanel
     */
    private JPanel userProcessContainer;
    private Education education;
    private CourseSchedule courseSchedule;
    DefaultTableModel dtm;

    public StudentRankingJPanel(JPanel userProcessContainer, Education education, CourseSchedule courseSchedule) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.education = education;
        this.courseSchedule = courseSchedule;
        dtm = (DefaultTableModel) tblStudentRanking.getModel();
        populateTable();
    }
    
    public void populateTable(){
        dtm.setRowCount(0);
        
    ArrayList<Student> studentList = education.getStudentsDirectory().getStudentList();
    List<Student> filteredStudents = studentList.stream().filter(student -> student.getGrades().containsKey(courseSchedule.getScheduleId())).collect(Collectors.toList());   
    filteredStudents.sort(Comparator.comparing(student -> student.getGrades().get(courseSchedule.getScheduleId()), Comparator.reverseOrder()));

    for(Student student: filteredStudents){
         Object[] row = new Object[5];
                row[0] = student;
                row[1] = student.getName();
                row[2] = student.getEmail();
                row[3] = student.getGrades().get(courseSchedule.getScheduleId());
                row[4] = student.getGpa();
                dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentRanking = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        tblStudentRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Email", "Grade", "GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudentRanking);
        if (tblStudentRanking.getColumnModel().getColumnCount() > 0) {
            tblStudentRanking.getColumnModel().getColumn(0).setResizable(false);
            tblStudentRanking.getColumnModel().getColumn(1).setResizable(false);
            tblStudentRanking.getColumnModel().getColumn(2).setResizable(false);
            tblStudentRanking.getColumnModel().getColumn(3).setResizable(false);
            tblStudentRanking.getColumnModel().getColumn(4).setResizable(false);
        }

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudentRanking;
    // End of variables declaration//GEN-END:variables
}
